OBJ=Nodetype.o HaffmanTree.o
CCFLAGS=-Wall

HaffmanTree.o: HaffmanTree.h HaffmanTree.h MaxHeap.h Nodetype.h
	g++ $(CCFLAGS) -c HaffmanTree.cpp
Nodetype.o: Nodetype.h Nodetype.cpp
	g++ $(CCFLAGS) -c Nodetype.cpp
